apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - openstackmachinetemplates
  verbs:
  - get
  - list
