# The openstackcluster resource is immutable, with the exception of the
# firewall rules list.  If anything else changes, then we need to trigger
# an upgrade via a resource rename.  Like other things e.g. osmts, we can
# base the name on inputs.  However in this case, something like adding
# availability zone support (which should in general be immutable), would
# also need to trigger a rename.  So to do that without making it based on
# the input, we need another method, i.e. a revision.  So if you decide to
# add support for a new immutable thing, you will also need to increment
# this number.  Got it??
{{- $cluster_revision := 1 }}
{{- $cluster_name_discriminated := printf "%v-%v" $.Release.Name (include "openstack.discriminator.cluster" $cluster_revision) }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        {{- range .Values.network.podCIDRs }}
        {{- printf "- %s" . | nindent 6 }}
        {{- end }}
    services:
      cidrBlocks:
        {{- range .Values.network.serviceCIDRs }}
        {{- printf "- %s" . | nindent 6 }}
        {{- end }}
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
    kind: OpenStackCluster
    name: {{ $cluster_name_discriminated }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ .Release.Name }}-control-plane
---
# Please read the comment at the top of this file before making any changes
# to this template.
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: {{ $cluster_name_discriminated }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  cloudName: {{ .Values.openstack.cloud }}
  identityRef:
    name: {{ .Release.Name }}-cloud-config
    kind: Secret
  apiServerLoadBalancer:
    enabled: true
    {{- with $api := .Values.api }}
      {{- with $allowList := $api.allowList }}
        {{- "allowedCidrs:" | nindent 4 }}
        {{- range $allowList }}
          {{- printf "- %s" . | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
  controlPlaneAvailabilityZones:
  - {{ .Values.openstack.computeFailureDomain }}
  managedSecurityGroups: true
  allowAllInClusterTraffic: true
  nodeCidr: {{ .Values.network.nodeCIDR }}
  dnsNameservers:
    {{- range .Values.network.dnsNameservers}}
    {{- printf "- %s" . | nindent 2 }}
    {{- end }}
  externalNetworkId: {{ .Values.openstack.externalNetworkID }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cloud-config
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
    clusterctl.cluster.x-k8s.io/move: "true"
  annotations:
    # This needs to be preserved until the cluster has deprovisioned.
    # See: https://github.com/argoproj/argo-cd/issues/3211
    argocd.argoproj.io/sync-wave: "-1"
data:
  clouds.yaml: {{ .Values.openstack.cloudsYAML }}
  cacert: {{ .Values.openstack.ca }}
