---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster.name" . }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        {{- range .Values.network.podCIDRs }}
        {{- printf "- %s" . | nindent 6 }}
        {{- end }}
    services:
      cidrBlocks:
        {{- range .Values.network.serviceCIDRs }}
        {{- printf "- %s" . | nindent 6 }}
        {{- end }}
    serviceDomain: "cluster.local"
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
    kind: OpenStackCluster
    name: {{ include "openstackcluster.name" . }}
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    name: {{ include "kubeadmcontrolplane.name" . }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackCluster
metadata:
  name: {{ include "openstackcluster.name" . }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
  annotations:
    # Let CAPO do this in its chosen order.
    argocd.argoproj.io/sync-options: Delete=false
spec:
  cloudName: {{ .Values.openstack.cloud }}
  identityRef:
    name: {{ include "cloudconfig.name" . }}
    kind: Secret
  apiServerLoadBalancer:
    enabled: true
    {{- with $api := .Values.api }}
      {{- with $allowList := $api.allowList }}
        {{- "allowedCidrs:" | nindent 4 }}
        {{- range $allowList }}
          {{- printf "- %s" . | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
  controlPlaneOmitAvailabilityZone: true
  managedSecurityGroups: true
  allowAllInClusterTraffic: true
  {{- if not .Values.network.subnetID }}
  nodeCidr: {{ .Values.network.nodeCIDR }}
  {{- end }}
  {{- if .Values.network.routerID }}
  router:
    id: {{ .Values.network.routerID }}
  {{- end }}
  {{- if .Values.network.networkID }}
  network:
    id: {{ .Values.network.networkID }}
  {{- end }}
  {{- if .Values.network.subnetID }}
  subnet:
    id: {{ .Values.network.subnetID }}
  {{- end }}
  dnsNameservers:
    {{- range .Values.network.dnsNameservers}}
    {{- printf "- %s" . | nindent 2 }}
    {{- end }}
  externalNetworkId: {{ .Values.openstack.externalNetworkID }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudconfig.name" . }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
    clusterctl.cluster.x-k8s.io/move: "true"
  annotations:
    # This needs to be preserved until the cluster has deprovisioned.
    # See: https://github.com/argoproj/argo-cd/issues/3211
    argocd.argoproj.io/sync-wave: "-1"
data:
  clouds.yaml: {{ .Values.openstack.cloudsYAML }}
  {{- if .Values.openstack.ca }}
  cacert: {{ .Values.openstack.ca }}
  {{- end }}
