---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-control-plane"
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  version: "{{ .Values.controlPlane.version }}"
  replicas: {{ .Values.controlPlane.replicas }}
  machineTemplate:
    infrastructureRef:
      kind: OpenStackMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      name: {{ .Release.Name }}-control-plane-{{ include "openstack.discriminator.control-plane" . }}
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: {{ "'{{ local_hostname }}'" }}
        kubeletExtraArgs:
          cloud-provider: external
          node-labels: {{- include "openstack.nodelabels.control-plane" . | nindent 12 }}
        taints:
          {{- include "openstack.taints.control-plane" . | nindent 8 }}
    joinConfiguration:
      nodeRegistration:
        name: {{ "'{{ local_hostname }}'" }}
        kubeletExtraArgs:
          cloud-provider: external
          node-labels: {{- include "openstack.nodelabels.control-plane" . | nindent 12 }}
        taints:
          {{- include "openstack.taints.control-plane" . | nindent 8 }}
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
        certSANs:
        - localhost
        - 127.0.0.1
        {{- with $api := .Values.api }}
          {{- with $sans := $api.certificateSANs }}
            {{- range $sans }}
              {{- printf "- %s" . | nindent 8 }}
            {{- end }}
          {{- end }}
        {{- end }}
      controllerManager:
        extraArgs:
          cloud-provider: external
      etcd:
        local:
          extraArgs:
            listen-metrics-urls: "http://0.0.0.0:2381"
      scheduler:
        extraArgs:
          authorization-always-allow-paths: "/healthz,/readyz,/livez,/metrics"
          bind-address: "0.0.0.0"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-control-plane-{{ include "openstack.discriminator.control-plane" . }}
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  template:
    spec:
      flavor: {{ .Values.controlPlane.machine.flavor }}
      image: {{ .Values.controlPlane.machine.image }}
      {{- if .Values.openstack.sshKeyName }}
      sshKeyName: {{ .Values.openstack.sshKeyName }}
      {{- end }}
      cloudName: {{ .Values.openstack.cloud }}
      identityRef:
        name: {{ .Release.Name }}-cloud-config
        kind: Secret
      {{- if .Values.controlPlane.machine.diskSize }}
      rootVolume:
        availabilityZone: {{ .Values.openstack.failureDomain }}
        diskSize: {{ .Values.controlPlane.machine.diskSize }}
      {{- end }}
