---
kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
metadata:
  name: "{{ .Release.Name }}-control-plane"
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controlPlane.replicas }}
  machineTemplate:
    infrastructureRef:
      kind: OpenStackMachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
      name: "{{ .Release.Name }}-control-plane"
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        name: {{ "'{{ local_hostname }}'" }}
        kubeletExtraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
          node-labels:
            {{- include "openstack.nodelabels.control-plane" . | nindent 12 }}
    clusterConfiguration:
      imageRepository: k8s.gcr.io
      apiServer:
        extraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
        extraVolumes:
        - name: cloud
          hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          readOnly: true
        certSans:
        - localhost
        - 127.0.0.1
        {{- with $api := .Values.kubernetes.api }}
          {{- with $sans := $api.certificateSANs }}
            {{- range $sans }}
              {{- printf "- %s" . | nindent 8 }}
            {{- end }}
          {{- end }}
        {{- end }}
      controllerManager:
        extraArgs:
          cloud-provider: openstack
          cloud-config: /etc/kubernetes/cloud.conf
        extraVolumes:
        - name: cloud
          hostPath: /etc/kubernetes/cloud.conf
          mountPath: /etc/kubernetes/cloud.conf
          readOnly: true
        - name: cacerts
          hostPath: /etc/certs/cacert
          mountPath: /etc/certs/cacert
          readOnly: true
    joinConfiguration:
      nodeRegistration:
        name: {{ "'{{ local_hostname }}'" }}
        kubeletExtraArgs:
          cloud-config: /etc/kubernetes/cloud.conf
          cloud-provider: openstack
          node-labels:
            {{- include "openstack.nodelabels.control-plane" . | nindent 12 }}
    files:
    - path: /etc/kubernetes/cloud.conf
      owner: root
      permissions: "0600"
      content: {{ .Values.openstack.cloudProviderConfiguration }}
      encoding: base64
    - path: /etc/certs/cacert
      owner: root
      permissions: "0600"
      content: {{ .Values.openstack.ca }}
      encoding: base64
  version: "{{ .Values.kubernetes.version }}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha5
kind: OpenStackMachineTemplate
metadata:
  name: {{ .Release.Name }}-control-plane
  labels:
    {{- include "openstackcluster.labels" . | nindent 4 }}
spec:
  template:
    spec:
      flavor: {{ .Values.controlPlane.flavor }}
      image: {{ .Values.openstack.image }}
      sshKeyName: {{ .Values.openstack.sshKeyName }}
      cloudName: {{ .Values.openstack.cloud }}
      identityRef:
        name: {{ .Release.Name }}-cloud-config
        kind: Secret
      {{- if .Values.controlPlane.diskSize }}
      roolVolume:
        diskSize: {{ .Values.controlPlane.diskSize }}
      {{- end }}
