{{ $values := .Values }}
{{ range $name, $pool := .Values.workloadPools }}

{{/*
Helm is a bit crap in that $. doesn't work in an include with a non-global scope.
To combat this, we build a custom context before handing off to thte template.
*/}}
{{ $context := dict "name" $name "pool" $pool "values" $values }}

{{/*
The resource names are common all over the place, so define in a canonical location.
*/}}
{{ $pool_name := printf "%v-pool-%v" $.Release.Name $name }}
{{ $pool_name_discriminated := printf "%v-pool-%v-%v" $.Release.Name $name (include "openstack.discriminator.workload" $context) }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $pool_name }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
  annotations:
    {{- include "openstackcluster.autoscalingAnnotations" $pool | nindent 4 }}
spec:
  clusterName: "{{ $.Release.Name }}"
  {{- if $pool.autoscaling }}{{ else }}
  replicas: {{ $pool.replicas }}
  {{- end }}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: "{{ $.Release.Name }}"
      version: "{{ $pool.version }}"
      failureDomain: {{ include "openstack.failureDomain.workload" $context }}
      bootstrap:
        configRef:
          name: {{ $pool_name_discriminated }}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ $pool_name_discriminated }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
        kind: OpenStackMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackMachineTemplate
metadata:
  name: {{ $pool_name_discriminated }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      cloudName: {{ $.Values.openstack.cloud }}
      identityRef:
        name: {{ $.Release.Name }}-cloud-config
        kind: Secret
      flavor: {{ $pool.machine.flavor }}
      image: {{ $pool.machine.image }}
      {{- if $.Values.openstack.sshKeyName }}
      sshKeyName: {{ $.Values.openstack.sshKeyName }}
      {{- end }}
      {{- if $pool.machine.diskSize }}
      rootVolume:
        availabilityZone: {{ include "openstack.failureDomain.workload" $context }}
        diskSize: {{ $pool.machine.diskSize }}
      {{- end }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ $pool_name_discriminated }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
spec:
  template:
    spec:
      files:
      {{- range $file := $pool.files }}
      - content: {{ $file.content }}
        encoding: base64
        owner: root
        path: {{ $file.path }}
        permissions: "0600"
      {{- end }}
      joinConfiguration:
        nodeRegistration:
          name: {{ "'{{ local_hostname }}'" }}
          kubeletExtraArgs:
            cloud-provider: external
            node-labels: {{- include "openstack.nodelabels.workload" $context | nindent 14 }}
          taints:
            {{- include "openstack.taints.workload" $ | nindent 10 }}
{{- end }}
