{{- $values := .Values }}
{{- range $name, $pool := .Values.workloadPools }}

{{/*
Helm is a bit crap in that $. doesn't work in an include with a non-global scope.
To combat this, we build a custom context before handing off to thte template.
*/}}
{{- $context := dict "name" $name "pool" $pool "values" $values }}

{{/*
The resource names are common all over the place, so define in a canonical location.
*/}}
{{- $pool_name := printf "%s-pool-%s" $.Release.Name ( $name | sha256sum | trunc 8 ) }}
{{- $pool_name_discriminated := printf "%s-pool-%s-%s"  $.Release.Name ( $name | sha256sum | trunc 8 ) ( include "openstack.discriminator.workload" $context ) }}

{{- if $values.legacyResourceNames }}
  {{- $pool_name = printf "%v-pool-%v" $.Release.Name $name }}
  {{- $pool_name_discriminated = printf "%v-pool-%v-%v" $.Release.Name $name (include "openstack.discriminator.workload" $context) }}
{{- end }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: {{ $pool_name }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
  annotations:
    # Let CAPO do this in its chosen order.
    argocd.argoproj.io/sync-options: Delete=false
    {{- include "pool.annotatations" $context | nindent 4 }}
    {{- include "openstackcluster.autoscalingAnnotations" $context | nindent 4 }}
spec:
  clusterName: {{ include "cluster.name" $ }}
  {{- if not $pool.autoscaling }}
  replicas: {{ $pool.replicas }}
  {{- end }}
  selector:
    matchLabels:
  template:
    spec:
      clusterName: {{ include "cluster.name" $ }}
      version: "{{ $pool.version }}"
      failureDomain: {{ include "openstack.failureDomain.compute.workload" $context }}
      bootstrap:
        configRef:
          name: {{ $pool_name_discriminated }}
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{ $pool_name_discriminated }}
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
        kind: OpenStackMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackMachineTemplate
metadata:
  name: {{ $pool_name_discriminated }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
  annotations:
    # Let CAPO do this in its chosen order.
    argocd.argoproj.io/sync-options: Delete=false
    {{- include "pool.annotatations" $context | nindent 4 }}
spec:
  template:
    spec:
      cloudName: {{ $.Values.openstack.cloud }}
      identityRef:
        name: {{ include "cloudconfig.name" $ }}
        kind: Secret
      flavor: {{ $pool.machine.flavor }}
      image: {{ $pool.machine.image }}
      {{- if $.Values.openstack.sshKeyName }}
      sshKeyName: {{ $.Values.openstack.sshKeyName }}
      {{- end }}
      {{- with $disk := $pool.machine.disk }}
      rootVolume:
        availabilityZone: {{ include "openstack.failureDomain.volume.workload" $context }}
        diskSize: {{ $disk.size }}
      {{- end }}
      {{- with $cluster := $.Values.cluster -}}
        {{- with $metadata := $cluster.serverMetadata -}}
          {{- printf "serverMetadata:" | nindent 6 }}
          {{- toYaml $metadata | nindent 8 }}
        {{- end }}
      {{- end }}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{ $pool_name_discriminated }}
  labels:
    {{- include "openstackcluster.labels" $ | nindent 4 }}
  annotations:
    # Let CAPO do this in its chosen order.
    argocd.argoproj.io/sync-options: Delete=false
    {{- include "pool.annotatations" $context | nindent 4 }}
spec:
  template:
    spec:
      files:
      {{- range $file := $pool.files }}
      - content: {{ $file.content }}
        encoding: base64
        owner: root
        path: {{ $file.path }}
        permissions: "0600"
      {{- end }}
      joinConfiguration:
        nodeRegistration:
          name: {{ "'{{ local_hostname }}'" }}
          kubeletExtraArgs:
            cloud-provider: external
            node-labels: {{- include "openstack.nodelabels.workload" $context | nindent 14 }}
          taints:
            {{- include "openstack.taints.workload" $ | nindent 10 }}
{{- end }}
