# Label domain for implicit labels defined in this chart.
labelDomain: eschercloud.ai

# OpenStack specific configuration.
# Contains credentials for the cloud, networking options and other
# Values in this object are considered immutable.
openstack:
  # Name of the cloud in clouds.yaml.
  cloud: my-cloud

  # cloud.yaml file, base64 encoded.
  cloudsYAML: Y2hhbmdlIG1lIQ==

  # External (public) network ID.
  externalNetworkID: b19ce45a-3278-48e4-8a0e-83100af68778

  # Openstack endpoint CA, base64 encoded.
  ca: Y2hhbmdlIG1lIQ==

  # SSH key.
  #
  # sshKeyName: foo

  # Compute failure domain name.  Workload pools can be distributed
  # across multiple failure domains, but default to this if not
  # present.  Control plane nodes are deployed in this failure domain.
  computeFailureDomain: nova

  # If volumes are defined for machine sets, this is the global default.
  # It can be overidden on a per-workload pool/control plane basis.
  # volumeFailureDomain: nova

# Cluster wide configuration.
#
# cluster:
  # Applies taints to all nodes on creation.  Once a node is provisioned you
  # will need to manually update these.
  # taints:
  # - key: node.cilium.io/agent-not-ready
  #   effect: NoSchedule
  #   value: 'true'
  #
  # Applies the following key/value pairs to all server instances.
  # serverMetadata:
  #   foo: bar

# Kubernetes API specific configuration.
#
# api:
#  # Allow only the selected network address prefixes access to the API.
#  allowList:
#  - 192.168.0.1/24
#
#  # Generate the API server certificate with a specific set of X.509
#  # subject alternative names, "localhost" and "127.0.0.1" are required
#  # by Kubernetes and added by default.
#  # Modifications to this list will trigger a control plane upgrade.
#  certificateSANs:
#  - foo.acme.com

# Control plane topology.
# Modifications to this object will trigger a control plane upgrade.
controlPlane:
  # Version of Kubernetes, should match that installed on the base images.
  version: v1.25.2

  # Number of control plane machines.
  replicas: 3

  # Defines the physical properties of a machine.
  # Modifications to this object will trigger a control plane upgrade.
  machine:
    # Openstack image name.
    image: ubuntu-2204-kubernetes-1.25.0

    # Control plane machine type.
    flavor: m1.large

    # Ephemeral disk size in GB.  If specified this overrides the default
    # size for the flavor.
    # diskSize: 80

# Workload pools topology.
# workloadPools:
#  # Pool name
#  default:
#    # Version of Kubernetes, should match that installed on the base images
#    # in order to improve provisioning and scaling time.
#    version: v1.25.2
#
#    # Number of workload machines.
#    replicas: 3
#
#    # Defines the physical properties of a machine.
#    # Modifications to these objects will trigger a affected workload pool upgrades.
#    machine:
#      # Openstack image name.
#      image: ubuntu-2204-kubernetes-1.25.0
#
#      # Workload machine type.
#      flavor: m1.large
#
#      # Ephemeral disk size in GB.  If specified this overrides the default
#      # size for the flavor.
#      diskSize: 160
#
#      # Failure domain to provision the pool in, defaults to openstack.failureDomain.
#      failureDomain: nova
#
#    # Labels to apply to the pool nodes.  The pool name will be applied
#    # automatically with the $(labelDomain)/node-pool label.  The failureDomain
#    # will be automatically added as the well known "topology.kubernetes.io/zone"
#    # label along with the "topology.kubernetes.io/region" label.  This is only
#    # intended for use on initial node bring up and will not trigger a rolling
#    # upgrade.
#    labels:
#      group: foo
#
#    # Files to include on the machine.  These are limited to base64 encoded,
#    # root owned and readable at present.  Like node labels above, this is only
#    # intended for use on initial node bring up and will not trigger a rolling
#    # upgrade.
#    files:
#    - path: /etc/cat
#      content: bWVvdw==
#
#    # Enable or disable cluster autoscaling.
#    # This object is considered immutable.
#    autoscaling:
#      # Set the scaling limits.
#      # Limits are required by cluster-autoscaler.
#      limits:
#        # Minimum number of replicas.
#        minReplicas: 0
#
#        # Maximum number of replicas.
#        maxReplicas: 10
#
#      # Set the scaler scheduling hints.
#      # These are only required when using scale-from-zero support
#      # as cluster-autoscaler is unable to determine these values without
#      # an active node.
#      # scheduler:
#        # Number of CPU cores.
#        cpu: 4
#
#        # Amount of memory.
#        memory: 32G
#
#        # Whether a GPU is present or not.
#        gpu:
#          # The GPU type.
#          type: nvidia.com/gpu
#
#          # The number of GPUs.
#          count: 1

# Kubernetes/OpenStack networking options.
# Network options are immutable, changes will not result in
# any modification to the cluster.
# This object is considered immutable.
network:
  # Network prefix nodes will be allocated from.
  nodeCIDR: 192.168.0.0/16

  # Network prefixes service VIPs will be allocated from.
  serviceCIDRs:
  - 172.16.0.0/12

  # Network prefixes pods will be allocated from.
  podCIDRs:
  - 10.0.0.0/8

  # DNS nameservers to use.
  dnsNameservers:
  - 8.8.8.8
