# OpenStack specific configuration.
# Contains credentials for the cloud, networking options and
# other OpenStack specific configuration.
openstack:
  # Name of the cloud in clouds.yaml.
  cloud:
  # cloud.yaml file, base64 encoded.
  cloudsYAML:
  # External (public) network ID.
  externalNetworkID:
  # Kubelet openstack configuration, base64 encoded.
  cloudProviderConfiguration:
  # Openstack endpoint CA, base64 encoded.
  ca:
  # Openstack image name.
  image:
  # SSH key.
  sshKeyName:
  # Region defines the topology region.
  # This will be applied as the topology.kubernetes.io/region label
  # to all nodes.
  region: eu-west-1
  # Global failure domain name.  Workload pools can be distributed
  # across multiple failure domains, but default to this if not
  # present.
  failureDomain: nova

# Kubernetes specific configuration.
# Contains the cluster version and other API realted configuration.
kubernetes:
  # Version of Kubernetes, should match that installed on the base images.
  version: v1.25.2
  # API configuration.
  # api:
  #   # Allow only the selected network address prefixes access to the API.
  #   allowList:
  #   - 192.168.0.1/24
  #   # Generate the API server certificate with a specific set of X.509
  #   # subject alternative names, "localhost" and "127.0.0.1" are required
  #   # by Kubernetes and added by default.
  #   certificateSANs:
  #   - foo.acme.com

# Control plane topology.
controlPlane:
  # Number of control plane machines.
  replicas: 3
  # Control plane machine type.
  flavor: m1.large
  # Ephemeral disk size in GB.  If specified this overrides the default
  # size for the flavor.
  diskSize: 80

# Workload pools topology.
workloadPools:
  # Pool name
  default:
    # Number of workload machines.
    replicas: 0
    # Enable or disable cluster autoscaling.
    autoscaling:
      # Set the scaling limits.
      # Limits are required by cluster-autoscaler.
      limits:
        # Minimum number of replicas.
        minReplicas: 0
        # Maximum number of replicas.
        maxReplicas: 10
      # Set the scaler scheduling hints.
      # These are only required when using scale-from-zero support
      # as cluster-autoscaler is unable to determine these values without
      # an active node.
      scheduler:
        # Number of CPU cores.
        cpu: 4
        # Amount of memory.
        memory: 32G
        # Whether a GPU is present or not.
        gpu:
          # The GPU type.
          type: nvidia.com/gpu
          # The number of GPUs.
          count: 1
    # Workload machine type.
    flavor: m1.large
    # Ephemeral disk size in GB.  If specified this overrides the default
    # size for the flavor.
    diskSize: 160
    # # Failure domain to provision the pool in, defaults to openstack.failureDomain.
    # failureDomain: nova
    # # Node labels to apply to the pool.  The pool name will be applied
    # # automatically with the eschercloud.ai/node-pool label.  The failureDomain
    # # will be automatically added as the well known topology.kubernetes.io/zone
    # # label.  This should not be used, as it's trivial to just label nodes yourself
    # # after provisioning, also a modification to this will result in an upgrade
    # # of the cluster, which is dumb because you could have done it yourself
    # # manually.
    # nodeLabels:
    #   group: foo

# Kubernetes/OpenStack networking options.
# Network options are immutable, changes will not result in
# any modification to the cluster.
network:
  # Network prefix nodes will be allocated from.
  nodeCIDR: 192.168.0.0/16
  # Network prefixes service VIPs will be allocated from.
  serviceCIDRs:
  - 172.16.0.0/12
  # Network prefixes pods will be allocated from.
  podCIDRs:
  - 10.0.0.0/8
  # DNS nameservers to use.
  dnsNameservers:
  - 8.8.8.8
