apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-openstack
  name: capo-serving-cert
  namespace: capo-system
spec:
  dnsNames:
  - capo-webhook-service.capo-system.svc
  - capo-webhook-service.capo-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capo-selfsigned-issuer
  secretName: capo-webhook-service-cert
