apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    cluster.x-k8s.io/provider: control-plane-kubeadm
  name: capi-kubeadm-control-plane-serving-cert
  namespace: capi-kubeadm-control-plane-system
spec:
  dnsNames:
  - capi-kubeadm-control-plane-webhook-service.capi-kubeadm-control-plane-system.svc
  - capi-kubeadm-control-plane-webhook-service.capi-kubeadm-control-plane-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: capi-kubeadm-control-plane-selfsigned-issuer
  secretName: capi-kubeadm-control-plane-webhook-service-cert
  subject:
    organizations:
    - k8s-sig-cluster-lifecycle
