name: Pull Request
on:
  pull_request:
    branches:
    - '*'
    tags-ignore:
    - '*'
jobs:
  helm-template:
    name: 'Test Helm Template'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Test
      run: make test
